const musicData = [
  {
    category: "happy",
    title: "Happy",
    singer: "Pharrel Williams",
    link: "https://open.spotify.com/track/60nZcImufyMA1MKQY3dcCH?si=8f3232c306bf4fe1",
  },
  {
    category: "happy",
    title: "Can't stop the feeling!",
    singer: "Justin Timberlake",
    link: "https://open.spotify.com/album/40LbnfieVTWtHrK24WQeEB?si=qehnL7o7Sd-v-SJfHF8_dA",
  },
  {
    category: "happy",
    title: "Walking on Sunshine",
    singer: "Katrina and the Waves",
    link: "https://open.spotify.com/track/05wIrZSwuaVWhcv5FfqeH0?si=f7ffa3ed6e2445d8",
  },
  {
    category: "happy",
    title: "Don't worry, be happy",
    singer: "Bobby McFerrin",
    link: "https://open.spotify.com/track/5YbgcwHjQhdT1BYQ4rxWlD?si=7e8108a9d2164228",
  },
  {
    category: "happy",
    title: "Levitating",
    singer: "Dua Lipa",
    link: "https://open.spotify.com/track/5nujrmhLynf4yMoMtj8AQF?si=62fb4b4a664d42c6",
  },
  {
    category: "happy",
    title: "Dancing Queen",
    singer: "ABBA",
    link: "https://open.spotify.com/track/0GjEhVFGZW8afUYGChu3Rr?si=5318755ed1b94abb",
  },
  {
    category: "happy",
    title: "Uptown Funk",
    singer: "Mark Ronson ft. Bruno Mars",
    link: "https://open.spotify.com/track/32OlwWuMpZ6b0aN2RZOeMS?si=63a7b81c8c264389",
  },
  {
    category: "happy",
    title: "Shake It Off",
    singer: "Taylor Swift",
    link: "https://open.spotify.com/track/0cqRj7pUJDkTCEsJkx8snD?si=591328efb17d4802",
  },
  {
    category: "happy",
    title: "Problem",
    singer: "Ariana Grande",
    link: "https://open.spotify.com/track/7vS3Y0IKjde7Xg85LWIEdP?si=df5bbb9f5bb644e9",
  },
  {
    category: "happy",
    title: "All About That Bass",
    singer: "Meghan Trainor",
    link: "https://open.spotify.com/track/5jE48hhRu8E6zBDPRSkEq7?si=99b6f03277764b6e",
  },
  {
    category: "happy",
    title: "Haven't Met You Yet",
    singer: "Michael Bublé",
    link: "https://open.spotify.com/track/4fIWvT19w9PR0VVBuPYpWA?si=bbf25275cf0f439a",
  },
  {
    category: "happy",
    title: "Sugar",
    singer: "Maroon 5",
    link: "https://open.spotify.com/track/5d6Mjuu2uCGRPYpFjGpCX5?si=8053ab45fcdf4de5",
  },
  {
    category: "happy",
    title: "Try Everything",
    singer: "Shakira",
    link: "https://open.spotify.com/track/1N3dZ7TTWO6VcD4Y3hHYLZ?si=71c09621fd1a475a",
  },
  {
    category: "happy",
    title: "Roar",
    singer: "Katy Perry",
    link: "https://open.spotify.com/track/6F5c58TMEs1byxUstkzVeM?si=5d17f8477a024faf",
  },
  {
    category: "happy",
    title: "Good Life",
    singer: "OneRepublic",
    link: "https://open.spotify.com/track/6OtCIsQZ64Vs1EbzztvAv4?si=3689976992cd4fed",
  },
  {
    category: "happy",
    title: "Here Comes the Sun",
    singer: "The Beatles",
    link: "https://open.spotify.com/track/6dGnYIeXmHdcikdzNNDMm2?si=42b2f92f82c8499e",
  },
  {
    category: "happy",
    title: "Viva La Vida",
    singer: "Coldplay",
    link: "https://open.spotify.com/track/1mea3bSkSGXuIRvnydlB5b?si=3bc33db82a424944",
  },
  {
    category: "happy",
    title: "Treasure",
    singer: "Bruno Mars",
    link: "https://open.spotify.com/track/55h7vJchibLdUkxdlX3fK7?si=cecd69c93153406c",
  },
  {
    category: "happy",
    title: "Higher Love",
    singer: "Kygo ft. Whitney Houston",
    link: "https://open.spotify.com/track/6oJ6le65B3SEqPwMRNXWjY?si=98bd022e8cd94bbb",
  },
  {
    category: "happy",
    title: "Fight Song",
    singer: "Rachel Platten",
    link: "https://open.spotify.com/track/37f4ITSlgPX81ad2EvmVQr?si=b5b1b30f7b974506",
  },
  {
    category: "happy",
    title: "HandClap",
    singer: "Fitz and The Tantrums",
    link: "https://open.spotify.com/track/7j56HrjR9cGzvekvZY3Faz?si=c44cad5bcd504b88",
  },
  {
    category: "happy",
    title: "Dance Monkey",
    singer: "Tones and I",
    link: "https://open.spotify.com/track/2XU0oxnq2qxCpomAAuJY8K?si=2f93e83602104ae0",
  },
  {
    category: "happy",
    title: "Pumped Up Kicks",
    singer: "Foster The People",
    link: "https://open.spotify.com/track/7w87IxuO7BDcJ3YUqCyMTT?si=75936858f81a4560",
  },
  {
    category: "happy",
    title: "Price Tag",
    singer: "Jessie J",
    link: "https://open.spotify.com/track/2fTsFCKRFQ5M0igJgabnLA?si=1005f82c78dc4616",
  },
  {
    category: "happy",
    title: "Something Just Like This",
    singer: "The Chainsmokers & Coldplay",
    link: "https://open.spotify.com/track/6RUKPb4LETWmmr3iAEQktW?si=e3d9fc5053334a8b",
  },
  {
    category: "happy",
    title: "Raise Your Glass",
    singer: "P!nk",
    link: "https://open.spotify.com/track/1gv4xPanImH17bKZ9rOveR?si=4a35b5a3e53e4153",
  },
  {
    category: "happy",
    title: "On Top of the World",
    singer: "Imagine Dragons",
    link: "https://open.spotify.com/track/213x4gsFDm04hSqIUkg88w?si=bc08ea468f734b40",
  },
  {
    category: "happy",
    title: "I'm Yours",
    singer: "Jason Mraz",
    link: "https://open.spotify.com/track/1EzrEOXmMH3G43AXT1y7pA?si=8029e02660b04cc5",
  },
  {
    category: "happy",
    title: "Girls Just Want to Have Fun",
    singer: "Cyndi Lauper",
    link: "https://open.spotify.com/track/4y1LsJpmMti1PfRQV9AWWe?si=956c9727f4224b3f",
  },
  {
    category: "happy",
    title: "Hey Ya!",
    singer: "OutKast",
    link: "https://open.spotify.com/track/2PpruBYCo4H7WOBJ7Q2EwM?si=bb76c18a4de8449b",
  },
  {
    category: "happy",
    title: "Good as Hell",
    singer: "Lizzo",
    link: "https://open.spotify.com/track/07Oz5StQ7GRoygNLaXs2pd?si=0a90d063f18d4d82",
  },
  {
    category: "happy",
    title: "Shape of You",
    singer: "Ed Sheeran",
    link: "https://open.spotify.com/track/7qiZfU4dY1lWllzX7mPBI3?si=8d388e39591946b8",
  },
  {
    category: "happy",
    title: "Marvin Gaye",
    singer: "Charlie Puth, Meghan Trainor",
    link: "https://open.spotify.com/track/3rKYiySCDMUKTw5kGVVhaa?si=13773b04585c4c23",
  },
  {
    category: "happy",
    title: "Love On Top",
    singer: "Beyoncé",
    link: "https://open.spotify.com/track/34h7O0d0ToOB60zYSFkGKH?si=543745315d784720",
  },
  {
    category: "happy",
    title: "Sorry",
    singer: "Justin Bieber",
    link: "https://open.spotify.com/track/0JBq4P9Jpp37F1PteCgGL1?si=b14b303617cb48af",
  },
  {
    category: "happy",
    title: "Pompeii",
    singer: "Bastille",
    link: "https://open.spotify.com/track/7Fw5i56my24ZBnGS7hFX2n?si=7675082884204014",
  },
  {
    category: "happy",
    title: "Wake Me Up",
    singer: "Avicii",
    link: "https://open.spotify.com/track/0nrRP2bk19rLc0orkWPQk2?si=5504b378809e468e",
  },
  {
    category: "happy",
    title: "Good Feeling",
    singer: "Flo Rida",
    link: "https://open.spotify.com/track/2LEF1A8DOZ9wRYikWgVlZ8?si=c32fefc28b074a65",
  },
  {
    category: "happy",
    title: "Party Rock Anthem",
    singer: "LMFAO",
    link: "https://open.spotify.com/track/7mitXLIMCflkhZiD34uEQI?si=d7ae321bc7b74f25",
  },
  {
    category: "happy",
    title: "There's Nothing Holdin' Me Back",
    singer: "Shawn Mendes",
    link: "https://open.spotify.com/track/7JJmb5XwzOO8jgpou264Ml?si=3fbd0c8fdea54d52",
  },
  {
    category: "happy",
    title: "Party in the U.S.A.",
    singer: "Miley Cyrus",
    link: "https://open.spotify.com/track/3E7dfMvvCLUddWissuqMwr?si=47a869ed594d41c1",
  },
  {
    category: "happy",
    title: "Shut Up and Dance",
    singer: "Walk the Moon",
    link: "https://open.spotify.com/track/4kbj5MwxO1bq9wjT5g9HaA?si=9132695fc94246a4",
  },
  {
    category: "happy",
    title: "Timber",
    singer: "Pitbull ft. Kesha",
    link: "https://open.spotify.com/track/3cHyrEgdyYRjgJKSOiOtcS?si=b5ba0bf165374b6f",
  },
  {
    category: "happy",
    title: "Moves Like Jagger",
    singer: "Maroon 5",
    link: "https://open.spotify.com/track/1r299qCKBLgUS9XJ9m1kEx?si=9541b1738f864407",
  },
  {
    category: "happy",
    title: "Watermelon Sugar",
    singer: "Harry Styles",
    link: "https://open.spotify.com/track/6UelLqGlWMcVH1E5c4H7lY?si=56407c52d0e742db",
  },
  {
    category: "happy",
    title: "Dynamite",
    singer: "BTS",
    link: "https://open.spotify.com/track/5QDLhrAOJJdNAmCTJ8xMyW?si=03c9fdd9c5ac46c9",
  },
  {
    category: "happy",
    title: "good 4 u",
    singer: "Olivia Rodrigo",
    link: "https://open.spotify.com/track/6P4d1NWBCNIYZjzF9k1mVN?si=c76dbd24f3c249b5",
  },
  {
    category: "happy",
    title: "Peaches",
    singer: "Justin Bieber",
    link: "https://open.spotify.com/track/4iJyoBOLtHqaGxP12qzhQI?si=fab0b26d7718435f",
  },
  {
    category: "happy",
    title: "Say So",
    singer: "Doja Cat",
    link: "https://open.spotify.com/track/3Dv1eDb0MEgF93GpLXlucZ?si=11869290d28d4898",
  },
  {
    category: "happy",
    title: "Positions",
    singer: "Ariana Grande",
    link: "https://open.spotify.com/track/35mvY5S1H3J2QZyna3TFe0?si=68d321a8d17a475d",
  },
  {
    category: "happy",
    title: "Señorita",
    singer: "Shawn Mendes & Camila Cabello",
    link: "https://open.spotify.com/track/0TK2YIli7K1leLovkQiNik?si=d90861c59a3c4242",
  },
  {
    category: "happy",
    title: "Midnight Sky",
    singer: "Miley Cyrus",
    link: "https://open.spotify.com/track/4i2qxFEVVUi8yOYoxB8TCX?si=b54b8355bab44ab8",
  },
  {
    category: "happy",
    title: "Bad Habits",
    singer: "Ed Sheeran",
    link: "https://open.spotify.com/track/3rmo8F54jFF8OgYsqTxm5d?si=420586f4de5a423d",
  },
  {
    category: "happy",
    title: "Heat Waves",
    singer: "Glass Animals",
    link: "https://open.spotify.com/track/3USxtqRwSYz57Ewm6wWRMp?si=0383f4bd7a424598",
  },
  {
    category: "happy",
    title: "MONTERO (Call Me By Your Name)",
    singer: "Lil Nas X",
    link: "https://open.spotify.com/track/67BtfxlNbhBmCDR2L2l8qd?si=878b78c26b054457",
  },
  {
    category: "happy",
    title: "Feel Special",
    singer: "TWICE",
    link: "https://open.spotify.com/track/3Hz3tTQwOdM6XkA0ALB2G9?si=c17f21fb3e4347e8",
  },
  {
    category: "happy",
    title: "How You Like That",
    singer: "BLACKPINK",
    link: "https://open.spotify.com/track/6bvZRLLkBKkmgpBJTTj3QK?si=c9d3f0aec16a4244",
  },
  {
    category: "happy",
    title: "Red Flavor",
    singer: "Red Velvet",
    link: "https://open.spotify.com/track/7nKQ5WAcjnG48knyLuo8gO?si=28d311ec214c4f01",
  },
  {
    category: "happy",
    title: "WANNABE",
    singer: "ITZY",
    link: "https://open.spotify.com/track/4pspYVQGFHLPEFgQPD1J7e?si=f4e11df64c4b45e9",
  },
  {
    category: "happy",
    title: "VERY NICE",
    singer: "SEVENTEEN",
    link: "https://open.spotify.com/track/1Rrj7KyS2R6SP9CQMDJW1w?si=6d0b6b9c295f4e62",
  },
  {
    category: "happy",
    title: "Power",
    singer: "EXO",
    link: "https://open.spotify.com/track/53YZi9zgTnF0Py0K6ejyWz?si=9be61563eb9747fb",
  },
  {
    category: "happy",
    title: "HIP",
    singer: "MAMAMOO",
    link: "https://open.spotify.com/track/24nK8tW7Pt3Inh2utttuoG?si=380c7a0c93294052",
  },
  {
    category: "happy",
    title: "We Go Up",
    singer: "NCT DREAM",
    link: "https://open.spotify.com/track/26vOBLHS116a4WNUVlvAUW?si=2d206e4c16584cbd",
  },
  {
    category: "happy",
    title: "Blue Hour",
    singer: "TXT",
    link: "https://open.spotify.com/track/3ObPkJQAgjAhTwYvDhPrAW?si=d86c1220efd14272",
  },
  {
    category: "happy",
    title: "MAGO",
    singer: "GFRIEND",
    link: "https://open.spotify.com/track/46WaBBaEHzgbN88Ew0nh50?si=636c571ce6b34f23",
  },
  {
    category: "happy",
    title: "View",
    singer: "SHINee",
    link: "https://open.spotify.com/track/46E1ic6n099e76t5J1TbHn?si=eb11181701504089",
  },
  {
    category: "happy",
    title: "Pporappippam",
    singer: "Sunmi",
    link: "https://open.spotify.com/track/7oQh96s9YemWG3A4zkIbrU?si=80507f1ce2ff4f38",
  },
  {
    category: "happy",
    title: "Gashina",
    singer: "Sunmi",
    link: "https://open.spotify.com/track/0jFHMDRXxKaREor3hBEEST?si=c07933d98fdd4c4a",
  },
  {
    category: "happy",
    title: "Back Door",
    singer: "Stray Kids",
    link: "https://open.spotify.com/track/0XuepwFJUcKN8T5zTqoP0F?si=7693acac8d92461c",
  },
  {
    category: "happy",
    title: "Panorama",
    singer: "IZ*ONE",
    link: "https://open.spotify.com/track/0CnpSTdL9l5vQM4YnzXtyo?si=f5e6e1e68b11484d",
  },
  {
    category: "happy",
    title: "Jopping",
    singer: "SuperM",
    link: "https://open.spotify.com/track/5WrEilrRI5cIW0DxMvQYPZ?si=4b69c921dc94424c",
  },
  {
    category: "happy",
    title: "Ko Ko Bop",
    singer: "EXO",
    link: "https://open.spotify.com/track/5EzitieoPnjyKHAq0gfRMa?si=a6ac6300439b41d0",
  },
  {
    category: "happy",
    title: "Peek-A-Boo",
    singer: "Red Velvet",
    link: "https://open.spotify.com/track/42tFTth2jcF7iSo0RBjfJF?si=daeb78b866954f1d",
  },
  {
    category: "happy",
    title: "Ice Cream",
    singer: "BLACKPINK",
    link: "https://open.spotify.com/track/1cdbkpZ3q1KYZDNSrOpdkb?si=ed5153a4532143b8",
  },
  {
    category: "happy",
    title: "God's Menu",
    singer: "Stray Kids",
    link: "https://open.spotify.com/track/4XPXrcpyNr30Km6aPiflJy?si=2febf09facf244d9",
  },
  {
    category: "happy",
    title: "Love Scenario",
    singer: "IKON",
    link: "https://open.spotify.com/track/3d3ELsqKlQ7WA0a10Isu3l?si=b444838186f44126",
  },
  {
    category: "happy",
    title: "Bestfriend",
    singer: "IKON",
    link: "https://open.spotify.com/track/1AhfmrzSrDmOIstpRO9wTI?si=d64643c44e6c4198",
  },
  {
    category: "happy",
    title: "Darari",
    singer: "Treasure",
    link: "https://open.spotify.com/track/0dcnrLo8s1rhjm8euGjI4n?si=81375e2883214d68",
  },
  {
    category: "happy",
    title: "Make A Wish (Birthday Song)",
    singer: "NCT U",
    link: "https://open.spotify.com/track/1Q5SpQeocfNXefx76svqkl?si=a832c3e39fdd4c30",
  },
  {
    category: "happy",
    title: "Polaroid Love",
    singer: "Enhypen",
    link: "https://open.spotify.com/track/5elW2CKSoqjYoJ32AGDxf1?si=d416ec00b3ad4ddb",
  },
  {
    category: "happy",
    title: "Psycho",
    singer: "Red Velvet",
    link: "https://open.spotify.com/track/3CYH422oy1cZNoo0GTG1TK?si=7f1c60d54c584e6b",
  },
  {
    category: "happy",
    title: "MORE & MORE",
    singer: "Twice",
    link: "https://open.spotify.com/track/3omvXShuRPM3zbDpWYqf5g?si=0ebc3ecc19844b2b",
  },
  {
    category: "happy",
    title: "Lovesick Girls",
    singer: "BLACKPINK",
    link: "https://open.spotify.com/track/1GMufNnkKAnPLnqKJ5HHxW?si=83a0eb46af74405a",
  },
  {
    category: "happy",
    title: "Dolphin",
    singer: "Oh My Girl",
    link: "https://open.spotify.com/track/5gpojs9yi3nm8aC3BOg6q5?si=7b73069a6b4349ea",
  },
  {
    category: "sadness",
    title: "That’s Okay",
    singer: "D.O.",
    link: "https://open.spotify.com/track/2Ghu1DdMwxS3VAyB7i38Wo?si=53fb60dc6d3e403f",
  },
  {
    category: "sadness",
    title: "Someone You Loved",
    singer: "Lewis Capaldi",
    link: "https://open.spotify.com/track/7qEHsqek33rTcFNT9PFqLf",
  },
  {
    category: "sadness",
    title: "Everything I wanted",
    singer: "Billie Eillish",
    link: "https://open.spotify.com/track/3ZCTVFBt2Brf31RLEnCkWJ",
  },
  {
    category: "sadness",
    title: "Easy On Me",
    singer: "Adele",
    link: "https://open.spotify.com/track/46IZ0fSY2mpAiktS3KOqds",
  },
  {
    category: "sadness",
    title: "you broke me first",
    singer: "Tate McRae",
    link: "https://open.spotify.com/track/45bE4HXI0AwGZXfZtMp8JR",
  },
  {
    category: "sadness",
    title: "Ghost",
    singer: "Justin Bieber",
    link: "https://open.spotify.com/track/6I3mqTwhRpn34SLVafSH7G",
  },
  {
    category: "sadness",
    title: "I'm not the Only One",
    singer: "Sam Smith",
    link: "https://open.spotify.com/track/7795WJLVKJoAyVoOtCWqXN?si=55bfba1d005e4998",
  },
  {
    category: "sadness",
    title: "Break My Heart",
    singer: "Dua Lipa",
    link: "https://open.spotify.com/track/017PF4Q3l4DBUiWoXk4OWT",
  },
  {
    category: "sadness",
    title: "Happier Than Ever",
    singer: "Billie Eilish",
    link: "https://open.spotify.com/track/4RVwu0g32PAqgUiJoXsdF8",
  },
  {
    category: "sadness",
    title: "Circles",
    singer: "Post Malone",
    link: "https://open.spotify.com/track/21jGcNKet2qwijlDFuPiPb",
  },
  {
    category: "sadness",
    title: "First Man",
    singer: "Camila Cabello",
    link: "https://open.spotify.com/track/6TRt2bniIq0EIlrDlje7b8?si=c61f99c1666247d8",
  },
  {
    category: "sadness",
    title: "when the party's over",
    singer: "Billie Eillish",
    link: "https://open.spotify.com/track/43zdsphuZLzwA9k4DJhU0I?si=cb004884cdc24453",
  },
  {
    category: "sadness",
    title: "Love in the dark",
    singer: "Adele",
    link: "https://open.spotify.com/track/0DuWDLjriRPjDRoPgaCslY?si=b581666e9ccb480b",
  },
  {
    category: "sadness",
    title: "Courage to Change",
    singer: "Sia",
    link: "https://open.spotify.com/track/2MbgQKWhoii8bqsMBWWWgA?si=7e23ae0abe7443d9",
  },
  {
    category: "sadness",
    title: "Scars To Your Beautiful",
    singer: "Alessia Cara",
    link: "https://open.spotify.com/track/42ydLwx4i5V49RXHOozJZq?si=3be574cff3be45bf",
  },
  {
    category: "sadness",
    title: "Modern Loneliness",
    singer: "Lauv",
    link: "https://open.spotify.com/track/18ioFJkxW5B0hOXE0l2ddw?si=028303b088864a1a",
  },
  {
    category: "sadness",
    title: "Anyone",
    singer: "Demi Lovato",
    link: "https://open.spotify.com/track/3XabMu0mJaQmrqz57UkEZI?si=5eedd856221c4b10",
  },
  {
    category: "sadness",
    title: "Lose You to Love Me",
    singer: "Selena Gomez",
    link: "https://open.spotify.com/track/4l0Mvzj72xxOpRrp6h8nHi?si=e98b6686f1974cc0",
  },
  {
    category: "sadness",
    title: "Supermarket Flowers",
    singer: "Ed Sheeran",
    link: "https://open.spotify.com/track/4VuS959DSpr82t3qBqCrWG?si=593f90347214401e",
  },
  {
    category: "sadness",
    title: "idontwannabeyouanymore",
    singer: "Billie Eilish",
    link: "https://open.spotify.com/track/41zXlQxzTi6cGAjpOXyLYH?si=fd5f3877cbf94097",
  },
  {
    category: "sadness",
    title: "Out of Love",
    singer: "Alessia Cara",
    link: "https://open.spotify.com/track/4WzhjxvLP95y7AMDy0Atwb?si=de9682ca24a14cf6",
  },
  {
    category: "sadness",
    title: "My Blood",
    singer: "Twenty One Pilots ",
    link: "https://open.spotify.com/track/5HeKOKc4phmLn8e4I7EkzD?si=a1ee8c5b306a4629",
  },
  {
    category: "sadness",
    title: "Sober",
    singer: "Demi Lovato",
    link: "https://open.spotify.com/track/0STK94RxUulYqWzwFlyAb5?si=d0f76197f9694546",
  },
  {
    category: "sadness",
    title: "Summertime Sadness",
    singer: "Lana Del Rey",
    link: "https://open.spotify.com/track/3BJe4B8zGnqEdQPMvfVjuS?si=49205b62ebde4f27",
  },
  {
    category: "sadness",
    title: "Fire on Fire",
    singer: "Sam Smith",
    link: "https://open.spotify.com/track/7t3Xdbufg7q2onVsR8RBdY?si=aab65f70573e465a",
  },
  {
    category: "sadness",
    title: "deja vu",
    singer: "Olivia Rodrigo",
    link: "https://open.spotify.com/track/6HU7h9RYOaPRFeh0R3UeAr?si=737a8b434d1f4380",
  },
  {
    category: "sadness",
    title: "Spring Day",
    singer: "BTS",
    link: "https://open.spotify.com/track/2j1fFjWHCI9KJSwcuYAOyF?si=616f64e598b14b5d",
  },
  {
    category: "sadness",
    title: "Stay",
    singer: "Blackpink",
    link: "https://open.spotify.com/track/3tP6QKbXvtrxiDI7QwKyUf?si=2dd2d6ffbe0d4128",
  },
  {
    category: "sadness",
    title: "Miracles in December",
    singer: "EXO",
    link: "https://open.spotify.com/track/7HrCnwDvbtCKSZtpNDmII9?si=fd5dfaa4f5764a56",
  },
  {
    category: "sadness",
    title: "Through the Night",
    singer: "IU",
    link: "https://open.spotify.com/track/3P3UA61WRQqwCXaoFOTENd?si=3597c04820ff4066",
  },
  {
    category: "sadness",
    title: "Feel Special",
    singer: "TWICE",
    link: "https://open.spotify.com/track/3Hz3tTQwOdM6XkA0ALB2G9?si=cb92318722df4978",
  },
  {
    category: "sadness",
    title: "Magic Shop",
    singer: "BTS",
    link: "https://open.spotify.com/track/37nOpaUof3d4Xsmr6moAiI?si=dd19c548667540c3",
  },
  {
    category: "sadness",
    title: "Fine",
    singer: "Taeyeon",
    link: "https://open.spotify.com/track/6CdUgvL597jWmW4w8P5kHs?si=116ecce4ab0541d5",
  },
  {
    category: "sadness",
    title: "Eight",
    singer: "IU",
    link: "https://open.spotify.com/track/0pYacDCZuRhcrwGUA5nTBe?si=36392261cb5c4c64",
  },
  {
    category: "sadness",
    title: "Life Goes On",
    singer: "BTS",
    link: "https://open.spotify.com/track/5FVbvttjEvQ8r2BgUcJgNg?si=1907c79eacc2483e",
  },
  {
    category: "sadness",
    title: "Don't Go",
    singer: "EXO",
    link: "https://open.spotify.com/track/1Acgi7wxVD9OF3iQnFe8Q4?si=3d6552a61b854028",
  },
  {
    category: "sadness",
    title: "Congratulations",
    singer: "Day6",
    link: "https://open.spotify.com/track/13z3GfR6WzmLUDxBHO3amM?si=97a708134b6e4bcf",
  },
  {
    category: "sadness",
    title: "You Are",
    singer: "GOT7",
    link: "https://open.spotify.com/track/5THFfbp23EcJsygTyiBDzJ?si=a09d5c55f32c4fd6",
  },
  {
    category: "sadness",
    title: "Four Seasons",
    singer: "Taeyeon",
    link: "https://open.spotify.com/track/4ytyLpIwUXbdFsNOvgNnmP?si=9bdab277e6f84055",
  },
  {
    category: "sadness",
    title: "11:11",
    singer: "Taeyeon",
    link: "https://open.spotify.com/track/67QGnT1Vdfuuy4HkLTUVjj?si=083c33dc1f3a4278",
  },
  {
    category: "sadness",
    title: "Love Poem",
    singer: "IU",
    link: "https://open.spotify.com/track/7HrE6HtYNBbGqp5GmHbFV0?si=5e7f340a5556409b",
  },
  {
    category: "sadness",
    title: "Palette",
    singer: "IU",
    link: "https://open.spotify.com/track/3y7ByLZ05tluscOTRgEJ9Y?si=98520b77f06c4fcf",
  },
  {
    category: "sadness",
    title: "Last Goodbye",
    singer: "AKMU",
    link: "https://open.spotify.com/track/0x50cQ1pZeV4xl737GhKBk?si=ab8f100c63c84be5",
  },
  {
    category: "sadness",
    title: "Give Love",
    singer: "AKMU",
    link: "https://open.spotify.com/track/2A3ShNautqXezP1lFDePwa?si=fc2590ac92d14e30",
  },
  {
    category: "sadness",
    title: "Someone Like You",
    singer: "Adele",
    link: "https://open.spotify.com/track/3bNv3VuUOKgrf5hu3YcuRo?si=0aa4522ae8824d9e",
  },
  {
    category: "sadness",
    title: "Hurt",
    singer: "Johnny Cash",
    link: "https://open.spotify.com/track/28cnXtME493VX9NOw9cIUh?si=20c6ee59ca044d54",
  },
  {
    category: "sadness",
    title: "Fix You",
    singer: "Coldplay",
    link: "https://open.spotify.com/track/7LVHVU3tWfcxj5aiPFEW4Q?si=839c42b8ba474d2e",
  },
  {
    category: "sadness",
    title: "Skinny Love",
    singer: "Bon Iver",
    link: "https://open.spotify.com/track/3B3eOgLJSqPEA0RfboIQVM?si=c51e5c263d414dcb",
  },
  {
    category: "sadness",
    title: "When We Were Young",
    singer: "Adele",
    link: "https://open.spotify.com/track/6O5TrlFWTYvznd9fMC0VvU?si=a4ad182ad07f4377",
  },
  {
    category: "sadness",
    title: "Let Her Go",
    singer: "Passenger",
    link: "https://open.spotify.com/track/2pUpNOgJBIBCcjyQZQ00qU?si=1717b095bf8c4df7",
  },
  {
    category: "sadness",
    title: "All I Want",
    singer: "Kodaline",
    link: "https://open.spotify.com/track/0NlGoUyOJSuSHmngoibVAs?si=5bf1a5904ada4a88",
  },
  {
    category: "sadness",
    title: "Yesterday",
    singer: "The Beatles",
    link: "https://open.spotify.com/track/3BQHpFgAp4l80e1XslIjNI?si=d7d223d57e7e4bd6",
  },
  {
    category: "sadness",
    title: "The Night We Met",
    singer: "Lord Huron",
    link: "https://open.spotify.com/track/3hRV0jL3vUpRrcy398teAU?si=1101a8391b2c4f6d",
  },
  {
    category: "sadness",
    title: "Tears in Heaven",
    singer: "Eric Clapton ",
    link: "https://open.spotify.com/track/1kgdslQYmeTR4thk9whoRw?si=ac6f7ebeab1d45d9",
  },
  {
    category: "sadness",
    title: "The Scientist",
    singer: "Coldplay",
    link: "https://open.spotify.com/track/75JFxkI2RXiU7L9VXzMkle?si=36842983da804e15",
  },
  {
    category: "sadness",
    title: "Make You Feel My Love",
    singer: "Adele",
    link: "https://open.spotify.com/track/273QnyCvJB65rScHJ1nPZb?si=9315343e97904275",
  },
  {
    category: "sadness",
    title: "Say Something",
    singer: "A Great Big World ft. Christina Aguilera ",
    link: "https://open.spotify.com/track/6Vc5wAMmXdKIAM7WUoEb7N?si=b0f19db0f55042a6",
  },
  {
    category: "sadness",
    title: "Let It Be",
    singer: "The Beatles ",
    link: "https://open.spotify.com/track/7iN1s7xHE4ifF5povM6A48?si=ba068bfda2fb4e7a",
  },
  {
    category: "sadness",
    title: "Jar of Hearts",
    singer: "Christina Perri ",
    link: "https://open.spotify.com/track/0HZhYMZOcUzZKSFwPOti6m?si=607452063f924d95",
  },
  {
    category: "sadness",
    title: "Misery",
    singer: "Maroon 5",
    link: "https://open.spotify.com/track/557idQwt2bQnRz9CI0zguR?si=588cf5c1088048d6",
  },

  {
    category: "fear",
    title: "Weightless",
    singer: "Marconi Union ",
    link: "https://open.spotify.com/track/6kkwzB6hXLIONkEk9JciA6?si=a5cf0053e97544ff",
  },
  {
    category: "fear",
    title: "Breathe Me",
    singer: "Sia",
    link: "https://open.spotify.com/track/7jqzZyJJLrpkRFYGpkqSK6?si=1473ae1486ed46dd",
  },
  {
    category: "fear",
    title: "Clair de Lune",
    singer: "Claude Debussy",
    link: "https://open.spotify.com/track/405HNEYKGDifuMcAZvqrqA?si=9cf07d0c13664cba",
  },
  {
    category: "fear",
    title: "Hallelujah",
    singer: "Jeff Buckley",
    link: "https://open.spotify.com/track/3pRaLNL3b8x5uBOcsgvdqM?si=ebd81a5155a5411b",
  },
  {
    category: "fear",
    title: "Sunset Lover",
    singer: "Petit Biscuit",
    link: "https://open.spotify.com/track/0hNduWmlWmEmuwEFcYvRu1?si=ca7da4a78aed4747",
  },
  {
    category: "fear",
    title: "River Flows in You",
    singer: "Yiruma",
    link: "https://open.spotify.com/track/2agBDIr9MYDUducQPC1sFU?si=6fa6d983282c4f8a",
  },
  {
    category: "fear",
    title: "The Night We Met",
    singer: "Lord Huron",
    link: "https://open.spotify.com/track/3hRV0jL3vUpRrcy398teAU?si=1d202ce6fff6474e",
  },
  {
    category: "fear",
    title: "Holocene",
    singer: "Bon Iver",
    link: "https://open.spotify.com/track/35KiiILklye1JRRctaLUb4?si=876d0bb5c59d461c",
  },
  {
    category: "fear",
    title: "Skinny Love",
    singer: "Bon Iver",
    link: "https://open.spotify.com/track/3B3eOgLJSqPEA0RfboIQVM?si=0325df994f7f4e05",
  },
  {
    category: "fear",
    title: "Bloom",
    singer: "The paper kites",
    link: "https://open.spotify.com/track/1HMQmOWrkieKYWlFsjUP3D?si=143acdb968084312",
  },
  {
    category: "fear",
    title: "Lost in Japan",
    singer: "Shawn Mendes",
    link: "https://open.spotify.com/track/2QZ7WLBE8h2y1Y5Fb8RYbH?si=96a6535c43634fb0",
  },
  {
    category: "fear",
    title: "In My Blood",
    singer: "Shawn Mendes",
    link: "https://open.spotify.com/track/2QZ7WLBE8h2y1Y5Fb8RYbH?si=96a6535c43634fb0",
  },
  {
    category: "fear",
    title: "Slow Dancing in a Burning Room",
    singer: "John Mayer",
    link: "https://open.spotify.com/track/2jdAk8ATWIL3dwT47XpRfu?si=1351cbf4044f4ed5",
  },
  {
    category: "fear",
    title: "Sign of the times",
    singer: "Harry Styles",
    link: "https://open.spotify.com/track/5Ohxk2dO5COHF1krpoPigN?si=cb7e3b62b92541d2",
  },
  {
    category: "fear",
    title: "Chasing Cars",
    singer: "Snow Patrol",
    link: "https://open.spotify.com/track/5hnyJvgoWiQUYZttV4wXy6?si=eb21dc74b7ee4903",
  },
  {
    category: "fear",
    title: "Say You Won't Let Go",
    singer: "James Arthur",
    link: "https://open.spotify.com/track/5uCax9HTNlzGybIStD3vDh?si=9bde67123c7440d1",
  },
  {
    category: "fear",
    title: "Jealous",
    singer: "Labrinth",
    link: "https://open.spotify.com/track/4G92yYrUs0cvY7G41YRI0z?si=d1dd5ca0bffc4a12",
  },
  {
    category: "fear",
    title: "You Are the Reason",
    singer: "Calum Scott",
    link: "https://open.spotify.com/track/69vToJ9BMbbLlFZo7k7A7B?si=40a224d0d02b407f",
  },
  {
    category: "fear",
    title: "Let Her Go",
    singer: "Passenger",
    link: "https://open.spotify.com/track/2pUpNOgJBIBCcjyQZQ00qU?si=aa52123778ba4b23",
  },
  {
    category: "fear",
    title: "Come Away with Me",
    singer: "Norah Jones",
    link: "https://open.spotify.com/track/6jGnykaS6TkWp15utXSAeI?si=7a1b7a817da94c48",
  },
  {
    category: "fear",
    title: "Photograph",
    singer: "Ed Sheeran",
    link: "https://open.spotify.com/track/1HNkqx9Ahdgi1Ixy2xkKkL?si=7170b59b3f77482b",
  },
  {
    category: "fear",
    title: "Tears in Heaven",
    singer: "Eric Clapton",
    link: "https://open.spotify.com/track/1kgdslQYmeTR4thk9whoRw?si=6be1e362c708428a",
  },
  {
    category: "fear",
    title: "Home",
    singer: "Michael Bublé",
    link: "https://open.spotify.com/track/3lyLqIn8mybyEFTs8JJaLf?si=db7874b474344316",
  },
  {
    category: "fear",
    title: "Thinking Out Loud",
    singer: "Ed Sheeran",
    link: "https://open.spotify.com/track/34gCuhDGsG4bRPIf9bb02f?si=47c0b39e8d504949",
  },
  {
    category: "fear",
    title: "The A Team",
    singer: "Ed Sheeran",
    link: "https://open.spotify.com/track/1VdZ0vKfR5jneCmWIUAMxK?si=90b3cd32c11e499d",
  },
  {
    category: "fear",
    title: "Happier",
    singer: "Ed Sheeran",
    link: "https://open.spotify.com/track/2RttW7RAu5nOAfq6YFvApB?si=ddf445087564421e",
  },
  {
    category: "fear",
    title: "Perfect",
    singer: "Ed Sheeran",
    link: "https://open.spotify.com/track/0tgVpDi06FyKpA1z0VMD4v?si=a27114325acd45ec",
  },
  {
    category: "fear",
    title: "Say Something",
    singer: "A Great Big World ft. Christina Aguilera",
    link: "https://open.spotify.com/track/6Vc5wAMmXdKIAM7WUoEb7N?si=3227f9350e4e41da",
  },
  {
    category: "fear",
    title: "Gravity",
    singer: "Sara Bareilles",
    link: "https://open.spotify.com/track/4oa14QBfWRDfJy2agySy0L?si=f52866412b8f457d",
  },
  {
    category: "fear",
    title: "I'm Yours",
    singer: "Jason Mraz",
    link: "https://open.spotify.com/track/1EzrEOXmMH3G43AXT1y7pA?si=9832008ecaf24395",
  },
  {
    category: "fear",
    title: "Dreams",
    singer: "Fleetwood Mac",
    link: "https://open.spotify.com/track/1lbXEepatjRVjoG8pZMtdp?si=47cc1a374aa340e2",
  },
  {
    category: "fear",
    title: "Unchained Melody",
    singer: "The Righteous Brothers",
    link: "https://open.spotify.com/track/2qhASBzpbFhPRtrnZ5lLnz?si=4ad86e5ccf564b76",
  },
  {
    category: "fear",
    title: "Tenerife Sea",
    singer: "Ed Sheeran",
    link: "https://open.spotify.com/track/1HbcclMpw0q2WDWpdGCKdS?si=ded9133657d544ae",
  },
  {
    category: "fear",
    title: "Let Go",
    singer: "Frou Foru",
    link: "https://open.spotify.com/track/3xKTpGCsafXzV4muM1Hpl3?si=28771c613c444e1b",
  },
  {
    category: "fear",
    title: "Somewhere Only We Know",
    singer: "Keane",
    link: "https://open.spotify.com/track/1SKPmfSYaPsETbRHaiA18G?si=0ab01add8488409b",
  },
  {
    category: "fear",
    title: "The Only Exception",
    singer: "Paramore ",
    link: "https://open.spotify.com/track/7JIuqL4ZqkpfGKQhYlrirs?si=0928298c44244f44",
  },
  {
    category: "fear",
    title: "Everybody Hurts",
    singer: "R.E.M. ",
    link: "https://open.spotify.com/track/6PypGyiu0Y2lCDBN1XZEnP?si=b2a13f7ed4434e0f",
  },
  {
    category: "fear",
    title: "Yellow",
    singer: "Coldplay",
    link: "https://open.spotify.com/track/3AJwUDP919kvQ9QcozQPxg?si=b4f504fa6c4b4336",
  },
  {
    category: "fear",
    title: "Heartbeats",
    singer: "José González ",
    link: "https://open.spotify.com/track/16j0oMDsmn2aeAewzF1NUi?si=9aec1e20845d4da8",
  },
  {
    category: "fear",
    title: "Wicked Game",
    singer: "Chris Isaak ",
    link: "https://open.spotify.com/track/7w5AOd6HrDIHewHfpABEss?si=a5cdc13ba43b49a3",
  },
  {
    category: "fear",
    title: "High Hopes",
    singer: "Kodaline ",
    link: "https://open.spotify.com/track/6KkyuDhrEhR5nJVKtv9mCf?si=861835b5801841bb",
  },
  {
    category: "fear",
    title: "Beneath Your Beautiful",
    singer: "Labrinth ft. Emeli Sandé ",
    link: "https://open.spotify.com/track/2EcsgXlxz99UMDSPg5T8RF?si=c6a811b410fd4922",
  },
  {
    category: "fear",
    title: "Keep Your Head Up",
    singer: "Ben Howard ",
    link: "https://open.spotify.com/track/5fpEDGQX0Ah3utGnFYulQZ?si=05351ebd86724ded",
  },
  {
    category: "fear",
    title: "Shelter",
    singer: "Birdy",
    link: "https://open.spotify.com/track/75HUxEyYVoVnO4ZfAU9dfp?si=9d7fbaca1f674092",
  },
  {
    category: "fear",
    title: "Landslide",
    singer: "Fleetwood Mac",
    link: "https://open.spotify.com/track/5ihS6UUlyQAfmp48eSkxuQ?si=fcf03d5df4f5466e",
  },
  {
    category: "fear",
    title: "Fast Car",
    singer: "Tracy Chapman",
    link: "https://open.spotify.com/track/2M9ro2krNb7nr7HSprkEgo?si=668f9c8d09c44ec9",
  },
  {
    category: "fear",
    title: "Falling",
    singer: "Harry Styles ",
    link: "https://open.spotify.com/track/1ZMiCix7XSAbfAJlEZWMCp?si=d6c6ebeb8e1042b8",
  },
  {
    category: "fear",
    title: "In the Arms of an Angel",
    singer: "Sarah McLachlan",
    link: "https://open.spotify.com/track/0iYKHMyRUmKHXgexjHeHhp?si=5da73cdafa98438c",
  },
  {
    category: "fear",
    title: "Drops of Jupiter",
    singer: "Train ",
    link: "https://open.spotify.com/track/2hKdd3qO7cWr2Jo0Bcs0MA?si=3598bba70d6542e1",
  },
  {
    category: "fear",
    title: "Let It Go",
    singer: "James Bay ",
    link: "https://open.spotify.com/track/3nnG7AM9QopHVPEuLX3Khk?si=54305090166949cc",
  },
  {
    category: "fear",
    title: "Rolling in the Deep",
    singer: "Adele",
    link: "https://open.spotify.com/track/4OSBTYWVwsQhGLF9NHvIbR?si=3274bdaf6bd24ffc",
  },
  {
    category: "fear",
    title: "Breathe",
    singer: "Taylor Swift ft. Colbie Caillat ",
    link: "https://open.spotify.com/track/7HC7R2D8WjXVcUHJyEGjRs?si=cff95d1dbc9d45bb",
  },
  {
    category: "fear",
    title: "From the Dining Table",
    singer: "Harry Styles",
    link: "https://open.spotify.com/track/1IF5UcqRO42D12vYwceOY6?si=0e6ddbba64f44c40",
  },
  {
    category: "fear",
    title: "How to Save a Life",
    singer: "The Fray ",
    link: "https://open.spotify.com/track/5fVZC9GiM4e8vu99W0Xf6J?si=d29a9b25058a49ed",
  },
  {
    category: "fear",
    title: "Runaway",
    singer: "Aurora",
    link: "https://open.spotify.com/track/1v1oIWf2Xgh54kIWuKsDf6?si=3c1bb7fe5b2e420c",
  },
  {
    category: "fear",
    title: "Skin",
    singer: "Rag'n'Bone Man ",
    link: "https://open.spotify.com/track/6y2Kaz9QI01XBKJ8mTb7Pf?si=e899020852ed4714",
  },
  {
    category: "fear",
    title: "Rise Up",
    singer: "Andra Day",
    link: "https://open.spotify.com/track/0tV8pOpiNsKqUys0ilUcXz?si=ebd27cc043364f65",
  },
  {
    category: "fear",
    title: "Not About Angels",
    singer: "Birdy ",
    link: "https://open.spotify.com/track/5sF7hdYvhrcgNq8NZjfK8L?si=f80c82532e7048a7",
  },
  {
    category: "fear",
    title: "Brave",
    singer: "Sara Bareilles",
    link: "https://open.spotify.com/track/6Uy6K3KdmUdAfelUp0SeXn?si=e763d4abe2d74926",
  },
  {
    category: "fear",
    title: "Cold Little Heart",
    singer: "Michael Kiwanuka",
    link: "https://open.spotify.com/track/0qprlw0jfsW4H9cG0FFE0Z?si=bbfbc69a629d4751",
  },
  {
    category: "fear",
    title: "Hurt",
    singer: "Johnny Cash",
    link: "https://open.spotify.com/track/28cnXtME493VX9NOw9cIUh?si=599089e6bdac459b",
  },
  {
    category: "fear",
    title: "Ocean Eyes",
    singer: "Billie Eilish",
    link: "https://open.spotify.com/track/7hDVYcQq6MxkdJGweuCtl9?si=626523846871452d",
  },
  {
    category: "fear",
    title: "Lovely",
    singer: "Billie Eilish & Khalid",
    link: "https://open.spotify.com/track/0u2P5u6lvoDfwTYjAADbn4?si=4bd936d2fb584394",
  },
  {
    category: "fear",
    title: "Stay With Me",
    singer: "Sam Smith",
    link: "https://open.spotify.com/track/5Nm9ERjJZ5oyfXZTECKmRt?si=468e70b8149c46b0",
  },
  {
    category: "fear",
    title: "A Little Bit Yours",
    singer: "JP Saxe ",
    link: "https://open.spotify.com/track/00cBcYOlnHoXX9ver3cmdE?si=5d78c20cf7764a01",
  },
  {
    category: "fear",
    title: "i love you",
    singer: "Billie Eilish ",
    link: "https://open.spotify.com/track/6CcJMwBtXByIz4zQLzFkKc?si=165f0c5c09c649ce",
  },
  {
    category: "fear",
    title: "Heather",
    singer: "Conan Gray ",
    link: "https://open.spotify.com/track/4xqrdfXkTW4T0RauPLv3WA?si=b71a5266f14c4e8a",
  },
  {
    category: "fear",
    title: "Home",
    singer: "Edward Sharpe & The Magnetic Zeros ",
    link: "https://open.spotify.com/track/0cBPuDA3xUjR4Vh9o7CKy8?si=dc2a36430783406e",
  },
  {
    category: "fear",
    title: "Lost Boy",
    singer: "Ruth B.",
    link: "https://open.spotify.com/track/0zMzyHAeMvwq5CRstru1Fp?si=0925d6a5b0224f12",
  },
  {
    category: "fear",
    title: "Homesick",
    singer: "Dua Lipa",
    link: "https://open.spotify.com/track/5E5MqaS6eOsbaJibl3YeMZ?si=89706184f9d04b27",
  },
  {
    category: "fear",
    title: "Youth",
    singer: "Daughter",
    link: "https://open.spotify.com/track/2Ck6gblyk3UFCVPTh8o3TN?si=2462672f2fa64b37",
  },
  {
    category: "fear",
    title: "Blue Ain't Your Color",
    singer: "Keith Urban",
    link: "https://open.spotify.com/track/2CxmktXqJwP9KZv6WJtZCm?si=8b8255abf6464860",
  },
  {
    category: "fear",
    title: "Lost Without You",
    singer: "Freya Ridings",
    link: "https://open.spotify.com/track/3cWI6Hj9LQ0MfMuhw9uSMc?si=18de5011d9344b5e",
  },
  {
    category: "fear",
    title: "Lonely",
    singer: "Justin Bieber & Benny Blanco",
    link: "https://open.spotify.com/track/3S8jK1mGzQi24ilFb45DAZ?si=5d33631e2ee04609",
  },
  {
    category: "fear",
    title: "Falling Like the Stars",
    singer: "James Arthur",
    link: "https://open.spotify.com/track/395KzBy0bkb57dEvg6cfzJ?si=bb81aba6152348e0",
  },
  {
    category: "fear",
    title: "Issues",
    singer: "Julia Michaels",
    link: "https://open.spotify.com/track/7vu0JkJh0ldukEYbTVcqd0?si=b0c4b95d71dd414d",
  },
  {
    category: "fear",
    title: "Wild Horses",
    singer: "Birdy",
    link: "https://open.spotify.com/track/6IEc8l3p6Z5OBLMFg6Z2V1?si=bfd7045b370945a1",
  },
  {
    category: "fear",
    title: "I Found",
    singer: "Amber Run",
    link: "https://open.spotify.com/track/5zT5cMnMKoyruPj13TQXGx?si=e085b597f4a9461f",
  },
  {
    category: "fear",
    title: "Skinny Love",
    singer: "Birdy",
    link: "https://open.spotify.com/track/4RL77hMWUq35NYnPLXBpih?si=0a1c39429eed419f",
  },
  {
    category: "fear",
    title: "The Night We Met",
    singer: "Lord Huron",
    link: "https://open.spotify.com/track/3hRV0jL3vUpRrcy398teAU?si=10e083b5203f4f27",
  },

  {
    category: "anger",
    title: "Imagine",
    singer: "John Lennon",
    link: "https://open.spotify.com/track/1jYx1g0BXEqvr9bpZoDMS7?si=890ab27821de4dbf",
  },
  {
    category: "anger",
    title: "What a Wonderful World",
    singer: "Louis Armstrong",
    link: "https://open.spotify.com/track/29U7stRjqHU6rMiS8BfaI9?si=45db13fdb46446d9",
  },
  {
    category: "anger",
    title: "Somewhere Over the Rainbow",
    singer: "Judy Garland",
    link: "https://open.spotify.com/track/1cHyiXY9OY3KEn9G5thhr7?si=9a5a1c9807ff431b",
  },
  {
    category: "anger",
    title: "Let It Be",
    singer: "The Beatles",
    link: "https://open.spotify.com/track/7iN1s7xHE4ifF5povM6A48?si=a7791c35b7c4474c",
  },
  {
    category: "anger",
    title: "What's Going On",
    singer: "Marvin Gaye",
    link: "https://open.spotify.com/track/3Um9toULmYFGCpvaIPFw7l?si=9ca136d9e9e64ae1",
  },
  {
    category: "anger",
    title: "Can't Help Falling in Love",
    singer: "Elvis Presley",
    link: "https://open.spotify.com/track/44AyOl4qVkzS48vBsbNXaC?si=e5dae1d432d54d87",
  },
  {
    category: "anger",
    title: "I Will Always Love You",
    singer: "Whitney Houston",
    link: "https://open.spotify.com/track/4eHbdreAnSOrDDsFfc4Fpm?si=b1eb73399a574058",
  },
  {
    category: "anger",
    title: "Bridge Over Troubled Water",
    singer: "Simon & Garfunkel",
    link: "https://open.spotify.com/track/6l8EbYRtQMgKOyc1gcDHF9?si=0bc23b923e584e61",
  },
  {
    category: "anger",
    title: "Three Little Birds",
    singer: "Bob Marley",
    link: "https://open.spotify.com/track/7vggqxNKwd6xdRoYS0pQtM?si=89abd872a80d4529",
  },
  {
    category: "anger",
    title: "Weightless",
    singer: "Ludovico Einaudi",
    link: "https://open.spotify.com/track/6kkwzB6hXLIONkEk9JciA6?si=ce711f132fb74b3a",
  },
  {
    category: "anger",
    title: "Gymnopédie No. 1",
    singer: "Erik Satie",
    link: "https://open.spotify.com/track/5NGtFXVpXSvwunEIGeviY3?si=9491a40d70654d99",
  },
  {
    category: "anger",
    title: "Clair de Lune",
    singer: "Claude Debussy",
    link: "https://open.spotify.com/track/405HNEYKGDifuMcAZvqrqA?si=a0f0a9dba79b4154",
  },
  {
    category: "anger",
    title: "Morning Has Broken",
    singer: "Cat Stevens",
    link: "https://open.spotify.com/track/08iKq9eiXCQfD0uzNzzpbc?si=212040c372be4f28",
  },
  {
    category: "anger",
    title: "Nuvole Bianche (White Clouds)",
    singer: "Ludovico Einaudi",
    link: "https://open.spotify.com/track/3weNRklVDqb4Rr5MhKBR3D?si=6bdcc3e0e1aa4c43",
  },
  {
    category: "anger",
    title: "Watermark",
    singer: "Enya",
    link: "https://open.spotify.com/track/4vOQ55pOMyE6bQJJzm3kei?si=38c4717f1a2b4229",
  },
  {
    category: "anger",
    title: "Canon in D Major",
    singer: "Johann Pachelbel",
    link: "https://open.spotify.com/track/5rtQNhJkPVl6N2nQpwbbk0?si=649b4757ee754b5d",
  },
  {
    category: "anger",
    title: "Gymnopédie No. 3",
    singer: "Erik Satie",
    link: "https://open.spotify.com/track/0hZBK2IS2uKdWVwEWXX1vB?si=22fc7ad8c737438a",
  },
  {
    category: "anger",
    title: "Air on a G String",
    singer: "Johann Sebastian Bach",
    link: "https://open.spotify.com/track/2L5WJA8XcCnczIVhujMNcZ?si=017399f4589045a2",
  },
  {
    category: "anger",
    title: "Rain Sounds",
    singer: "Relaxing Rain Sounds for Sleep and Meditation",
    link: "https://open.spotify.com/track/5Z9PdFWRMPCAhLSri69ADv?si=a0049574b41544bd",
  },
  {
    category: "anger",
    title: "Ocean Waves Sounds",
    singer: "Relaxing Ocean Waves Sounds for Sleep and Meditation",
    link: "https://open.spotify.com/track/7sYRF3ebwkY6XYSl1y6Kzo?si=f11251bc94cc4759",
  },
  {
    category: "anger",
    title: "Forest Sounds",
    singer: "Relaxing Forest Sounds for Sleep and Meditation",
    link: "https://open.spotify.com/track/39dZxgC0nEUlKtDH4PJFz6?si=79984057b47d41ef",
  },
  {
    category: "anger",
    title: "Birdsong Sounds",
    singer: "Relaxing Birdsong Sounds for Sleep and Meditation",
    link: "https://open.spotify.com/track/3xg9aK5fKRnRmLQXUHjP4b?si=a6c67f3ce76f493b",
  },
  {
    category: "anger",
    title: "Waterfall Sounds",
    singer: "Relaxing Waterfall Sounds for Sleep and Meditation",
    link: "https://open.spotify.com/track/4m1qQOIYJ5Fa9TCDJkex8b?si=346132ad91bb4273",
  },
  {
    category: "anger",
    title: "Campfire Sounds",
    singer: "Relaxing Campfire Sounds for Sleep and Meditation",
    link: "https://open.spotify.com/track/0mO5XwEQyIQ2a3UhQZymnz?si=b66a19f67b1f4d01",
  },
  {
    category: "anger",
    title: "White Noise",
    singer: "Relaxing White Noise for Sleep and Meditation",
    link: "https://open.spotify.com/track/0sb1fCD9OSi43f1mMFbdsc?si=210d06b3470643ea",
  },
  {
    category: "anger",
    title: "Pink Noise",
    singer: "Relaxing Pink Noise for Sleep and Meditation",
    link: "https://open.spotify.com/track/1oBNH8mxBJpCy64sYhHOcw?si=f97bfbdf1fcb4373",
  },
  {
    category: "anger",
    title: "Brown Noise",
    singer: "Relaxing Brown Noise for Sleep and Meditation",
    link: "https://open.spotify.com/track/76jlu6pr45PmRDeZirYVJk?si=e0bc675af9d348ab",
  },
  {
    category: "anger",
    title: "ASMR Sounds",
    singer: "Relaxing ASMR Sounds for Sleep and Meditation",
    link: "https://open.spotify.com/track/4RH4QMllpsTWqd3Oznu3eP?si=8cfb1d23bb9449f9",
  },
  {
    category: "anger",
    title: "Smells Like Teen Spirit",
    singer: "Nirvana",
    link: "https://open.spotify.com/track/4CeeEOM32jQcH3eN9Q2dGj?si=dd2a8c6e514d4bb2",
  },
  {
    category: "anger",
    title: "Break Stuff",
    singer: "Limp Bizki",
    link: "https://open.spotify.com/track/5cZqsjVs6MevCnAkasbEOX?si=8e5746f69df748ef",
  },
  {
    category: "anger",
    title: "Killing in the Name",
    singer: "Rage Against The Machine",
    link: "https://open.spotify.com/track/59WN2psjkt1tyaxjspN8fp?si=24e05f6c77b248bf",
  },
  {
    category: "anger",
    title: "In the End",
    singer: "Linkin Park",
    link: "https://open.spotify.com/track/60a0Rd6pjrkxjPbaKzXjfq?si=be80d20b78ee4c0c",
  },
  {
    category: "anger",
    title: "Chop Suey!",
    singer: "System of a Down",
    link: "https://open.spotify.com/track/2DlHlPMa4M17kufBvI2lEN?si=49cf995626b84af9",
  },
  {
    category: "anger",
    title: "Du Hast",
    singer: "Rammstein",
    link: "https://open.spotify.com/track/5awDvzxWfd53SSrsRZ8pXO?si=fe3269b8d81d4fdb",
  },
  {
    category: "anger",
    title: "Enter Sandman",
    singer: "Metallica",
    link: "https://open.spotify.com/track/5sICkBXVmaCQk5aISGR3x1?si=27fa1598d97e4569",
  },
  {
    category: "anger",
    title: "Bodies",
    singer: "Drowning Pool",
    link: "https://open.spotify.com/track/7CpbhqKUedOIrcvc94p60Y?si=ba88f9ed6c164b9b",
  },
  {
    category: "anger",
    title: "Down with the Sickness",
    singer: "Disturbed",
    link: "https://open.spotify.com/track/40rvBMQizxkIqnjPdEWY1v?si=e9601033035f4043",
  },
  {
    category: "anger",
    title: "Papercut",
    singer: "Linkin Park",
    link: "https://open.spotify.com/track/1Vej0qeQ3ioKwpI6FUbRv1?si=426f2f9ba38a4705",
  },
  {
    category: "anger",
    title: "Last Resort",
    singer: "Papa Roach",
    link: "https://open.spotify.com/track/5W8YXBz9MTIDyrpYaCg2Ky?si=aeb770d5db2d47b8",
  },
  {
    category: "anger",
    title: "Headstrong",
    singer: "Trapt",
    link: "https://open.spotify.com/track/1AEYT6VxrxXPMoQUxsY0E4?si=aabc5d3d89bb43a1",
  },
  {
    category: "anger",
    title: "Faint",
    singer: "Linkin Park",
    link: "https://open.spotify.com/track/7AB0cUXnzuSlAnyHOqmrZr?si=c1fdf1a0c4b5492c",
  },
  {
    category: "anger",
    title: "Heavy",
    singer: "Linkin Park",
    link: "https://open.spotify.com/track/104buTcnP2AsxqB7U1FIZ4?si=fe0ef318b3154451",
  },
  {
    category: "anger",
    title: "Psychosocial",
    singer: "Slipknot",
    link: "https://open.spotify.com/track/3RAFcUBrCNaboRXoP3S5t1?si=84b68c2fe9a747fb",
  },
  {
    category: "anger",
    title: "Duality",
    singer: "Slipknot",
    link: "https://open.spotify.com/track/61mWefnWQOLf90gepjOCb3?si=a0699902b0e848d1",
  },
  {
    category: "anger",
    title: "Given Up",
    singer: "Linkin Park",
    link: "https://open.spotify.com/track/1fLlRApgzxWweF1JTf8yM5?si=7750626aaea747df",
  },
  {
    category: "anger",
    title: "Bleed It Out",
    singer: "Linkin Park",
    link: "https://open.spotify.com/track/0UFDKFqW2oGspYeYqo9wjA?si=e6fa33b5faa7424d",
  },
  {
    category: "anger",
    title: "Freak on a Leash",
    singer: "Korn",
    link: "https://open.spotify.com/track/6W21LNLz9Sw7sUSNWMSHRu?si=3c1ec181f29b4f55",
  },
  {
    category: "anger",
    title: "Before I Forget",
    singer: "Slipknot",
    link: "https://open.spotify.com/track/6wqJeItl3Vc3az4ZicSQAB?si=43ffe2da885a4da0",
  },
  {
    category: "anger",
    title: "Coming Undone",
    singer: "Korn",
    link: "https://open.spotify.com/track/3o7TMr6RmIusYH7Kkg7ujR?si=fe73408d97f94254",
  },
  {
    category: "anger",
    title: "One Step Closer",
    singer: "Linkin Park",
    link: "https://open.spotify.com/track/3K4HG9evC7dg3N0R9cYqk4?si=32736054afff4aff",
  },
  {
    category: "anger",
    title: "Stressed Out",
    singer: "Twenty One Pilots",
    link: "https://open.spotify.com/track/3CRDbSIZ4r5MsZ0YwxuEkn?si=259db61b954e45bc",
  },
  {
    category: "anger",
    title: "Believer",
    singer: "Imagine Dragons",
    link: "https://open.spotify.com/track/0pqnGHJpmpxLKifKRmU6WP?si=0149ded51a754719",
  },
  {
    category: "anger",
    title: "Demons",
    singer: "Imagine Dragons",
    link: "https://open.spotify.com/track/5qaEfEh1AtSdrdrByCP7qR?si=ab1395d2ef8741b5",
  },
  {
    category: "anger",
    title: "Animal I Have Become",
    singer: "Three Days Grace",
    link: "https://open.spotify.com/track/56sk7jBpZV0CD31G9hEU3b?si=90bee606cbbf43e7",
  },
  {
    category: "anger",
    title: "I Hate Everything About You",
    singer: "Three Days Grace",
    link: "https://open.spotify.com/track/6rUp7v3l8yC4TKxAAR5Bmx?si=9178e609d59f44ce",
  },
  {
    category: "anger",
    title: "Pain",
    singer: "Three Days Grace",
    link: "https://open.spotify.com/track/5PZ2cqh9Yem2g6cTSOLllz?si=fea2683aae184cae",
  },
  {
    category: "anger",
    title: "Riot",
    singer: "Three Days Grace",
    link: "https://open.spotify.com/track/1Q2fYlSdwuutWj3QplhY9q?si=0dc92d3fa7d04f7f",
  },
  {
    category: "anger",
    title: "Burn It Down",
    singer: "Linkin Park",
    link: "https://open.spotify.com/track/7oVEtyuv9NBmnytsCIsY5I?si=491cfb6a2aa8438f",
  },
  {
    category: "anger",
    title: "Breaking the Habit",
    singer: "Linkin Park",
    link: "https://open.spotify.com/track/3dxiWIBVJRlqh9xk144rf4?si=f10d7250f4684ec4",
  },
  {
    category: "anger",
    title: "Sick and Tired",
    singer: "Anastacia",
    link: "https://open.spotify.com/track/54s027DgaSJlvp1q2sdzTa?si=9682be3b427b4866",
  },
  {
    category: "anger",
    title: "Going Under",
    singer: "Evanescence",
    link: "https://open.spotify.com/track/3UygY7qW2cvG9Llkay6i1i?si=04bba2616bd74176",
  },
  {
    category: "anger",
    title: "Bring Me to Life",
    singer: "Evanescence",
    link: "https://open.spotify.com/track/0COqiPhxzoWICwFCS4eZcp?si=cdd72ef406d54bed",
  },
  {
    category: "anger",
    title: "Misery Business",
    singer: "Paramore",
    link: "https://open.spotify.com/track/3l9CW99AHtExIRV4hW2N5m?si=667659289db84eb0",
  },
  {
    category: "anger",
    title: "That's What You Get",
    singer: "Paramore",
    link: "https://open.spotify.com/track/0UY4FvG4f9JI6kBR1BlWrZ?si=e2fc24f86f4d40d5",
  },
  {
    category: "anger",
    title: "Ignorance",
    singer: "Paramore",
    link: "https://open.spotify.com/track/47No93LxERvV6MtOAmQzHS?si=e7a7687251094b0f",
  },
  {
    category: "anger",
    title: "Brick by Boring Brick",
    singer: "Paramore",
    link: "https://open.spotify.com/track/1a9YW7fATU351ok4zWjU7a?si=d94e7267984b4bda",
  },
  {
    category: "anger",
    title: "Monster",
    singer: "Paramore",
    link: "https://open.spotify.com/track/04BSvYghzdxjSJNpee36er?si=8b9c47ce806241aa",
  },
  {
    category: "anger",
    title: "Ain't It Fun",
    singer: "Paramore",
    link: "https://open.spotify.com/track/1j8z4TTjJ1YOdoFEDwJTQa?si=198b337817c64428",
  },
  {
    category: "anger",
    title: "Crushcrushcrush",
    singer: "Paramore",
    link: "https://open.spotify.com/track/4m9NfjevXsDVaLtM1kj0Sx?si=15e5ae10489b43c3",
  },
  {
    category: "anger",
    title: "Decode",
    singer: "Paramore",
    link: "https://open.spotify.com/track/1ZLtE9tSJdaUiIJ9YoKHQe?si=d7e5129f3171429f",
  },
  {
    category: "anger",
    title: "The Kill",
    singer: "Thirty Seconds to Mars",
    link: "https://open.spotify.com/track/0lP4HYLmvowOKdsQ7CVkuq?si=7b9e702ac5094bbb",
  },
  {
    category: "anger",
    title: "Closer",
    singer: "Nine Inch Nails",
    link: "https://open.spotify.com/track/5mc6EyF1OIEOhAkD0Gg9Lc?si=1be0eed7f1d84436",
  },
  {
    category: "anger",
    title: "Terrible Lie",
    singer: "Nine Inch Nails",
    link: "https://open.spotify.com/track/3o1nX61oecxnqXieA2ma0U?si=c5d0065d73414770",
  },
  {
    category: "anger",
    title: "March of the Pigs",
    singer: "Nine Inch Nails",
    link: "https://open.spotify.com/track/56NATwQKP7m64hFLFlKzXe?si=e9904be91db94fed",
  },
  {
    category: "anger",
    title: "Head Like a Hole",
    singer: "Nine Inch Nails",
    link: "https://open.spotify.com/track/3ckd4YA4LcD3j50rfIVwUe?si=034651f64c3c4430",
  },
  {
    category: "anger",
    title: "I Wanna Be Your Dog",
    singer: "The Stooges",
    link: "https://open.spotify.com/track/672N8DGGTOLCOgWe0koX5g?si=d0f4f7dd9eea4e00",
  },
  {
    category: "anger",
    title: "Search and Destroy",
    singer: "Iggy & The Stooges",
    link: "https://open.spotify.com/track/00sydAz6PeOxYzwG1dRIPi?si=442f21b1d275434a",
  },
  {
    category: "anger",
    title: "Welcome to the Jungle",
    singer: "Guns N' Roses",
    link: "https://open.spotify.com/track/0G21yYKMZoHa30cYVi1iA8?si=5ce4a3f1a9844801",
  },
  {
    category: "anger",
    title: "Sweet Child O' Mine",
    singer: "Guns N' Roses",
    link: "https://open.spotify.com/track/7snQQk1zcKl8gZ92AnueZW?si=0f5c5c245b5845de",
  },
  {
    category: "anger",
    title: "Paradise City",
    singer: "Guns N' Roses",
    link: "https://open.spotify.com/track/6eN1f9KNmiWEhpE2RhQqB5?si=0bdd66e610494709",
  },
];

if (process.env.NODE_ENV !== "production") {
  require("dotenv").config();
}

const mongoose = require("mongoose");
const Music = require("../models/music");

const dbUrl = process.env.DB_URL;

main().catch((err) => console.log(err));
async function main() {
  await mongoose.connect(dbUrl);
  console.log("Database Connected");
}

const seedDB = async function () {
  try {
    // Insert the music data
    await Music.insertMany(musicData);
    console.log("Data inserted successfully");
  } catch (error) {
    console.error("Error inserting data:", error);
  }
};

seedDB().then(() => {
  mongoose.connection.close();
});
